---
name: Publish RevealJS presentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'  # Use the appropriate Node.js version here

      - name: Install dependencies
        run: npm install

      - name: Build RevealJS presentation
        run: npm ci && npm run prepare 
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2